CREATE database exam_juanico;

use exam_juanico;

CREATE TABLE employees (
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(200) NOT NULL,
	contact VARCHAR(20) NOT NULL,
	address VARCHAR(200) NOT NULL,
	email VARCHAR(200) NOT NULL,
	birthday DATE NOT NULL,
	status SMALLINT(1) DEFAULT 1,
	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);